# Generated by Django 5.1.7 on 2025-08-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookaxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_axle_name', models.CharField(max_length=200)),
                ('model_axle_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookbridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_bridge_name', models.CharField(max_length=200)),
                ('model_bridge_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookclaimpart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_claimpart_name', models.CharField(max_length=200)),
                ('model_claimpart_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookclaimrecover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_claimrecover_name', models.CharField(max_length=200)),
                ('model_claimrecover_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookclutch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_clutch_name', models.CharField(max_length=200)),
                ('model_clutch_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookcompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_company_name', models.CharField(max_length=200)),
                ('model_company_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookengine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_engine_name', models.CharField(max_length=200)),
                ('model_engine_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booktechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_technic_name', models.CharField(max_length=200)),
                ('model_technic_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booktm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_tm_name', models.CharField(max_length=200)),
                ('model_tm_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=200)),
                ('engine_factory_number', models.CharField(max_length=200)),
                ('clutch_factory_number', models.CharField(max_length=200)),
                ('driven_axle_factory_number', models.CharField(max_length=200)),
                ('managed_bridge_factory_number', models.CharField(max_length=200)),
                ('agreement_number', models.CharField(max_length=200)),
                ('agreement_date', models.DateField()),
                ('receiver', models.CharField(max_length=300)),
                ('receiver_address', models.CharField(max_length=300)),
                ('configuration', models.CharField(max_length=400)),
                ('client_name', models.CharField(max_length=200)),
                ('driven_axle_model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookaxle')),
                ('managed_bridge_model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookbridge')),
                ('model_clutch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookclutch')),
                ('model_engine', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookengine')),
                ('model_technic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.booktechnic')),
                ('service_company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookcompanies')),
            ],
        ),
        migrations.CreateModel(
            name='Claimservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField()),
                ('claim_hours', models.IntegerField()),
                ('claim_description', models.TextField()),
                ('claim_used_parts', models.TextField(blank=True, null=True)),
                ('claim_finish_date', models.DateField()),
                ('claim_downtime', models.IntegerField()),
                ('claim_car', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.car')),
                ('claim_part', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookclaimpart')),
                ('claim_recover', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookclaimrecover')),
                ('claim_service_company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookcompanies')),
            ],
        ),
        migrations.CreateModel(
            name='Technicalmaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_date', models.DateField()),
                ('tm_hours', models.IntegerField()),
                ('tm_number', models.CharField(max_length=200)),
                ('tm_number_date', models.DateField()),
                ('tm_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.car')),
                ('tm_service_company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.bookcompanies')),
                ('tm_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silant.booktm')),
            ],
        ),
    ]
